### ISSUE TITLE
Update workflow diagram

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-emfcloud/coffee-editor#323]
The coffee editor seems to use an outdated version of the workflow diagram example. Do we have plans to update it to the latest state including new features?

**Comment by JonasHelming** [comment]
@planger @eneufeld

**Comment by cdamus** [comment]
For #315 it is necessary to update the workflow diagram example to support visualization of the new concept(s) that it adds to the workflow model. This requires changes in the workflow diagram example's home repository.

Could the workflow diagram example instead be subsumed into this Coffee Editor repository? For that matter, can we consolidate all of the coffee and workflow related content into this Coffee Editor example repository so that it may stand alone as a sample app built on the underlying frameworks?

**Comment by planger** [comment]
So far we've updated it on demand, as far as I know. (@eneufeld please correct if there is another plan)

Anyway, I'm sure it wouldn't be a great deal of work to update it. I'd recommend to wait for https://github.com/eclipse-glsp/glsp-server/pull/96 and potentially use this as a vehicle to drive the GLSP-plan to better separate an API for EMF backends and direct GModel manipulating backends (such as the examples included in GLSP).

I'm happy to help out with that!

@cdamus Yes, that is a good point. I recall that we've discussed this internally already some time ago.
I think the current situation is that this repo already hosts the workflow GLSP server code (as it implements a GLSP server that reads and writes to an EMF model), but it pulls the workflow GLSP client module from the GLSP examples. This has two reasons: (a) back then we wanted to show that you can use the same client with two different server implementations, and (b) we didn't want to duplicate the client code. However, I feel that this example has greater value if it is self-contained, also if it comes with a higher maintenance cost.
It would mean copying this module which isn't that much code anymore:
https://github.com/eclipse-glsp/glsp-client/tree/master/examples/workflow-glsp
What do you think?

On the long run the goal is to make the client code even leaner (by making it more and more generic and driven by the server) so that eventually only the rendering (SVG Views and CSS), visual feedback and maybe some client-only-specific behavior (such as specific direct editing capabilities) or IDE specific commands and shortcuts is in there. This way the client code would be less painful to maintain twice in the long run, as it hopefully becomes very lean.

We are already quite far with that endeavor but for example some boilerplate code, such as the [module configuration](https://github.com/eclipse-glsp/glsp-client/blob/1e5b4a8bae51a9595eee5285255cba1cd331a6fe/examples/workflow-glsp/src/di.config.ts#L118) is something that could still be simplified.
Here we are thinking about introducing "capabilities" into the protocol that is sent from the server to the client, so that the client can derive from that which modules it should include. This mechanism however needs to still allow to change that in the client code as it is the no.1 entry point for doing customizations (excluding modules and registering own ones instead).

Imho even more boilerplate code is in the IDE integration (Theia in particular):
https://github.com/eclipse-emfcloud/coffee-editor/tree/master/web/coffee-workflow-glsp-editor/src
But this has already been copied over to this repo anyway.

**Comment by JonasHelming** [comment]
Maybe this is a stupid comment, but would it also be an option to include the workflow client and server as a submodule?
I see Christians point of having a self-contained example, which is especially useful for the "addition of one node" example he currently does. However, having the workflow example independently of the coffee editor is actually also something we want...

**Comment by planger** [comment]
I agree that we should definitely keep the workflow examples in the client, server and integration repos of GLSP. Imho, we need to keep them anyway for testing and for having simpler examples.

Submodules could be an option, but it may in turn complicate things as the client may get out of sync with the server and Theia integration, which are maintained here, e.g. when we want to have coffee model specific examples like the "addition of a node type" example, which would have to be rebased whenever something in GLSP changes.

I think I tend to just copying those few files, but am open to any solution that allows having coffee-model-specific examples and allows us to keep the simple examples in the GLSP repo too.

**Comment by tortmayr** [comment]
I agree with Philip. Right now the coffee editor repo already contains the code for the (modelserver-based) workflow server and the theia-integration. We are only reusing the package for the sprotty/glsp workflow configuration. As Philip already mentioned this is a rather small package with just a few files so I think copying those files is fine.

**Comment by eneufeld** [comment]
I also agree that we should simply separate the glsp-example and the coffee editor workflow as the use cases are different now (thus copying the code).
Yes this means duplication of code, but we should strive toward reducing this as Philip pointed out.
